version: '3.9'
services:
  app:
    build: 
      context: .
      dockerfile: ./dockerfile
    volumes:
      - ./src:/src
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]

volumes:
  node_modules: