version: '3.9'
services:
  app:
    build: 
      context: .
      target: dev
    image: fire-app:1.0.0
    volumes:
      - type: bind
        source: ./src
        target: /src
      - type: volume
        source: node_modules
        target: /src/node_modules
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true

volumes:
  node_modules: